/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_785989_34.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_785989_2[] = { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_785989_33_axes[] = { 0 };
const uint32_t ei_dsp_config_785989_33_axes_size = 1;
ei_dsp_config_image_t ei_dsp_config_785989_33 = {
    33, // uint32_t blockId
    1, // int implementationVersion
    1, // int length of axes
    NULL, // named axes
    0, // size of the named axes array
    "Grayscale" // select channels
};

const uint8_t ei_dsp_blocks_785989_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_785989_2[ei_dsp_blocks_785989_2_size] = {
    { // DSP block 33
        33,
        1024, // output size
        &extract_image_features, // DSP function pointer
        (void*)&ei_dsp_config_785989_33, // pointer to config struct
        ei_dsp_config_785989_33_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_785989_33_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        nullptr, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_785989_34 = {
    .implementation_version = 1,
    .model = tflite_learn_785989_34,
    .model_size = tflite_learn_785989_34_len,
    .arena_size = tflite_learn_785989_34_arena_size
};

const uint8_t ei_output_tensors_indices_785989_34[1] = { 0 };
const uint8_t ei_output_tensors_size_785989_34 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_785989_34 = {
    .implementation_version = 1,
    .block_id = 34,
    .output_tensors_indices = ei_output_tensors_indices_785989_34,
    .output_tensors_size = ei_output_tensors_size_785989_34,
    .quantized = 1,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_785989_34,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_785989_2_size = 1;
const uint32_t ei_learning_block_785989_34_inputs[1] = { 33 };
const uint8_t ei_learning_block_785989_34_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_785989_2[ei_learning_blocks_785989_2_size] = {
    {
        34,
        &run_nn_inference,
        (void*)&ei_learning_block_config_785989_34,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_785989_34_inputs,
        ei_learning_block_785989_34_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_785989_34 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_785989_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_785989_2[ei_postprocessing_blocks_785989_2_size] = {
    {
        .block_id = 34,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_785989_34,
        .input_block_id = 34
    },
};

const uint8_t freeform_outputs_785989_2_size = 0;

uint32_t *freeform_outputs_785989_2 = nullptr;

const ei_impulse_t impulse_785989_2 = {
    .project_id = 785989,
    .project_owner = "willisk0612",
    .project_name = "Digits",
    .impulse_id = 2,
    .impulse_name = "Impulse #2",
    .deploy_version = 14,

    .nn_input_frame_size = 1024,
    .raw_sample_count = 1024,
    .raw_samples_per_frame = 1,
    .dsp_input_frame_size = 1024 * 1,
    .input_width = 32,
    .input_height = 32,
    .input_frames = 1,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_785989_2_size,
    .dsp_blocks = ei_dsp_blocks_785989_2,

    .learning_blocks_size = ei_learning_blocks_785989_2_size,
    .learning_blocks = ei_learning_blocks_785989_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_785989_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_785989_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_CAMERA,
    .fusion_string = "image",
    .slice_size = (1024/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 10,
    .categories = ei_classifier_inferencing_categories_785989_2,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_785989_2_size,
    .freeform_outputs = freeform_outputs_785989_2
};

ei_impulse_handle_t impulse_handle_785989_2 = ei_impulse_handle_t( &impulse_785989_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_785989_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_785989_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_785989_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_785989_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
